import { ApartmentType } from "./src/utils/dataTypes";

export const apartments: ApartmentType[] = [
  {
    id: 1,
    price: 200000,
    address: "Hacienda West, North Coast, Egypt",
    zipcode: 12314,
    bedrooms: 2,
    bathrooms: 1,
    compound: "Hacienda West",
    finished: false,
  },
  {
    id: 2,
    price: 2430520,
    address: "North Coast, Egypt",
    zipcode: 12314,
    bedrooms: 3,
    bathrooms: 2,
    compound: "Silversands",
    finished: true,
  },
  {
    id: 3,
    price: 17450000,
    address: "ZED East in New Cairo by Ora Developers",
    zipcode: 12314,
    bedrooms: 3,
    bathrooms: 2,
    compound: "ZED East",
    finished: true,
  },
  {
    id: 4,
    price: 200000,
    address: "Solare in North Coast by Misr Italia Properties",
    zipcode: 12290,
    bedrooms: 2,
    bathrooms: 1,
    compound: "Solare",
    finished: false,
  },
  {
    id: 5,
    price: 10501165,
    address: "June in North Coast by SODIC",
    zipcode: 18503,
    bedrooms: 3,
    bathrooms: 1,
    compound: "June",
    finished: true,
  },
];
